server:
  port: 8259

spring:
  application:
    name: java-jpa-playground
  config:
    import: "file:.env[.properties]"
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    #open-in-view: true
    generate-ddl: false
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 10
        use_sql_comments: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
    org.springframework.orm.jpa: debug
    org.springframework.orm.jpa.JpaTransactionManager: debug
    org.springframework.transaction: info
    org.springframework.transaction.interceptor: trace
    org.springframework.hibernate.cache: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate: info
    org.hibernate.sql: debug
    org.hibernate.stat: debug
    org.hibernate.cache: debug
    org.hibernate.type: debug
    org.hibernate.jdbc: debug
