server:
  port: 8259

spring:
  application:
    name: java-jpa-playground
  config:
    import: "file:.env[.properties]"
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    #open-in-view: true
    generate-ddl: false
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        generate_statistics: true
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 10
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    com.example.javajpaplayground: debug
    org.springframework.web.servlet.DispatcherServlet: debug
#    org.springframework.orm.jpa: info
#    org.springframework.orm.jpa.JpaTransactionManager: debug
#    org.springframework.transaction: info
#    org.springframework.transaction.interceptor: trace
#    org.springframework.hibernate.stat: debug
#    org.springframework.hibernate.cache: debug
    org.hibernate.orm.jdbc.bind: trace
